nelmio_cors:
    defaults:
        max_age: 3600
        allow_origin: ['*']
    paths:
        '^/':
            allow_headers: ['Accept', 'Content-Type']
            allow_methods: ['GET', 'POST', 'PUT', 'OPTIONS', 'DELETE']
            expose_headers: []
